### ISSUE TITLE
Question: is this production-ready?

### ISSUE THREAD

**Issue by giann** [bjornbytes/graphql-lua#19]
Is this production ready or is it missing some important features?

**Comment by bjornbytes** [comment]
At the time the initial version was written, it was a complete implementation that wasn't missing anything.  There has been some activity in the GraphQL spec since then, so there may be some aspects of this library that are out of date.  I think the most notable thing that's missing is Subscriptions.

I have heard of a few companies using this library with nginx, and you may be interested in [tarantool's GraphQL adapter](https://github.com/tarantool/graphql) which is built on this library.

Thanks for the interest!

**Comment by giann** [comment]
Perfect thanks!
